In [101]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn import neighbors
from sklearn import metrics

In [102]:
index = ['comp.graphics','sci.med']
train = fetch_20newsgroups(subset='train',
                           categories=index,
                           shuffle=True,
                           random_state=42,

                           )
target_name = train.target_names
print(target_name)

['comp.graphics', 'sci.med']


In [103]:
count_vectorizer = CountVectorizer()
X_train_counts = count_vectorizer.fit_transform(train.data)
#X_train_counts.shape
print(X_train_counts.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [104]:
#docs_new = ['science is good', 'OpenGL o the GPU is']
#X_new_counts = count_vectorizer.transform(docs_new)

In [105]:
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
print(X_train_tf.shape)

(1178, 24614)


In [106]:
docs_new = ['science is good', 'I need a new CPU and CPU', 'this is a third sentence']
X_new_counts = count_vectorizer.transform(docs_new)
X_new_tf = tf_transformer.transform(X_new_counts)

In [107]:
knn = neighbors.KNeighborsClassifier(n_neighbors=2,metric='minkowski',p=2)
knn = knn.fit(X_train_tf,train.target)

In [108]:
predicted = knn.predict(X_new_tf)
for x in predicted:
    print(index[x])

comp.graphics
comp.graphics
comp.graphics


In [109]:
test = fetch_20newsgroups(subset='test',
                           categories=index,
                           shuffle=True,
                           random_state=42,
                           )
x_test_count = count_vectorizer.transform(test.data)
x_test_tf = tf_transformer.transform(x_test_count)
predicted = knn.predict(x_test_tf)

print("Acc:", metrics.accuracy_score(test.target,predicted))
print(metrics.classification_report(test.target,predicted,target_names=test.target_names)),
metrics.confusion_matrix(test.target,predicted)

Acc: 0.8012738853503185
               precision    recall  f1-score   support

comp.graphics       0.80      0.80      0.80       389
      sci.med       0.81      0.80      0.80       396

     accuracy                           0.80       785
    macro avg       0.80      0.80      0.80       785
 weighted avg       0.80      0.80      0.80       785



array([[313,  76],
       [ 80, 316]], dtype=int64)